# Generated by Django 2.0.7 on 2018-07-18 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=2048)),
                ('url', models.CharField(max_length=4096, null=True)),
                ('title', models.CharField(max_length=2048, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('media_path', models.CharField(max_length=4096, null=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='URLTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_name', to='pages.Tags')),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_library', to='pages.Library')),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
