# Generated by Django 2.0.7 on 2018-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='access',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Group')], default=1),
        ),
        migrations.AddField(
            model_name='library',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
