# Generated by Django 2.0.7 on 2018-07-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_auto_20180718_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_buddy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autotag', models.BooleanField(default=False)),
                ('auto_summary', models.BooleanField(default=False)),
                ('usrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grouptable',
            name='user_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_set', to='pages.UserSettings'),
        ),
    ]
