# Generated by Django 2.0.7 on 2018-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180722_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='total_tags',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
