# Generated by Django 2.0.7 on 2018-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_usersettings_total_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='buddy_list',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
