# Generated by Django 2.0.7 on 2018-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_usersettings_buddy_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='group_dir',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='public_dir',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
