# Generated by Django 2.0.7 on 2018-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180723_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='save_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='save_png',
            field=models.BooleanField(default=False),
        ),
    ]
