# Generated by Django 2.0.7 on 2018-07-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180726_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='png_quality',
            field=models.PositiveSmallIntegerField(default=85),
        ),
    ]
