# Generated by Django 2.0.7 on 2018-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_usersettings_png_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='auto_archieve',
            field=models.BooleanField(default=False),
        ),
    ]
