# Generated by Django 2.0.7 on 2018-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_library_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='icon_url',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
