# Generated by Django 2.0.7 on 2018-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_library_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
