# Generated by Django 2.0.7 on 2018-08-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180805_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='auto_archieve',
            new_name='auto_archive',
        ),
    ]
