# Generated by Django 2.1 on 2018-09-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_usersettings_pagination_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='media_element',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='download_manager',
            field=models.CharField(default='wget {iurl} -O {output}', max_length=8192),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='media_streaming',
            field=models.BooleanField(default=False),
        ),
    ]
