# Generated by Django 2.1 on 2018-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_usersettings_pagination_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='directory_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=2048),
        ),
    ]
