# Generated by Django 2.1.2 on 2018-10-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_library_reader_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='reader_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'default'), (1, 'dark'), (2, 'light'), (3, 'gray')], default=0),
        ),
    ]
