# Generated by Django 2.1.2 on 2018-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20181011_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='reader_theme',
            field=models.PositiveSmallIntegerField(choices=[(0, 'default'), (1, 'dark'), (2, 'light'), (3, 'gray')], default=0),
        ),
    ]
