# Generated by Django 2.1.2 on 2018-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_usersettings_reader_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='subdir',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
