# Generated by Django 2.1.2 on 2018-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_library_subdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='icon_url',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='media_path',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='subdir',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='tags',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='url',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
